name: Deploy demo

on: [workflow_dispatch]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v3
      - name: Install Node ğŸœ
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install Deps ğŸ”§
        run: npm i --legacy-peer-deps
      - name: Build app for production ğŸ’¥
        run: npx nx build ngx-responsive-table-demo -c production
      #      - name: Setup Pages ğŸ”§
      #        uses: actions/configure-pages@v3
      #      - name: Upload artifact ğŸœ
      #        uses: actions/upload-pages-artifact@v2
      #        with:
      #          path: 'dist/apps/ngx-responsive-table-demo'
      #      - name: Deploy to GitHub Pages ğŸ’¥
      #        id: deployment
      #        uses: actions/deploy-pages@v2
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_dir: ./dist/apps/ngx-responsive-table-demo
          destination_dir: ngx-responsive-table-demo
